name: Build Release
on: [push]
jobs:
  Build-Windows-Release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Prepare Environment - NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build Windows Release
        run: |
          npm install
          npm run electron:build:win
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: Windows Release
          path: ./dist_electron/翼企云短信加密 Setup 1.0.0.exe
  Build-MacOS-Release:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Prepare Environment - NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build MacOS Release
        run: |
          npm install
          npm run electron:build:mac
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: MacOS Release
          path: ./dist_electron/翼企云短信加密-1.0.0.dmg
